### PR TITLE
remove non-cython method and get rid of the spa class

### LINKED ISSUE #44: Remove non-cython implementations for methods of the `sparse_stoch_mat` (`SparseStochMat`) class
_From [this comment](https://github.com/alexbovet/flow_stability/commit/2f8d2327637d178091152d66b90505dd77a80ec9#commitcomment-145738964)_

Since we keep `Cython` as installation requirement, we do not really need non-cython implementations in the package, as `cython` should always be available after a successful install.

We can remove the native python implementations.

### LINKED ISSUE #45: Get rid of the `SPA` class
_From [this](https://github.com/alexbovet/flow_stability/commit/2f8d2327637d178091152d66b90505dd77a80ec9#commitcomment-145662057) and [this](https://github.com/alexbovet/flow_stability/commit/2f8d2327637d178091152d66b90505dd77a80ec9#commitcomment-145739054) comment_

- Check if/where the `SPA` class is used (for both the c and python implementation)
- Remove them if unused
- If used, check if there is a performance gain, if not, replace with existing implementations from `scipy`

### PR DESCRIPTION
**Pull request by j-i-l**
Closes #45 

Closes #44

### CODE REVIEW

**Comment by j-i-l** [comment]
`flowstab.SPA` is now only still used in the `_cython_sparse_stoch.stoch_mat_add/sub` functions.

**Comment by j-i-l** [comment]
might need some adaptations once #49 is merged

**Comment by alexbovet** [comment]
Let's keep `flowstab.SPA` for the moment until we do some proper testing of it. 

> might need some adaptations once https://github.com/alexbovet/flow_stability/pull/49 is merged

What do you mean? can we merge this?

**Comment by j-i-l** [comment]
> Let's keep `flowstab.SPA` for the moment until we do some proper testing of it.
> 
> > might need some adaptations once #49 is merged
> 
> What do you mean? can we merge this?

The changes from #49 partially affect the same files, so we just need to update this branch and sort out the potential conflicts, then this is ok to merge.
I'll update and check it.

**Comment by j-i-l** [comment]
@alexbovet now is fine.

I'll then bring the branch for #12 up to date and the we can merge in all the testing

**Pull request merged**
