### PR TITLE
Sphinx based documentation

### LINKED ISSUE #2: Building a documentation with sphinx
- Setup basic structure
- GH action to build
- Decide on the styling
- Decide where to host the docs

### PR DESCRIPTION
**Pull request by j-i-l**
closes #2 

The package should get a web-based documentation.

The following tasks will be addressed in this pull request:

- Basic structure for a sphinx documentation
- Extracting documentations from docstrings
- Setup of GH actions to deploy the documentation

### CODE REVIEW

**Comment by alexbovet** [comment]
Hey, thanks! I quite like the Insegel theme. What is the advantage of readthedocs vs a github page?

**Comment by alexbovet** [comment]
Ok for readthedocs then!

**Comment by j-i-l** [comment]
Here is how it looks with Insegel:

https://github.com/alexbovet/flow_stability/suites/18746248617/artifacts/1091735429

**Comment by j-i-l** [comment]
@alexbovet On ReadTheDocs there is always someone that 'hosts' the documentation. I would recommend that you are the one hosting it. But I'm also fine with hosting it on my account.

If you want to host it, then:

- sign in to readthedocs.org with your github account (or any other sign in method)
- under https://readthedocs.org/dashboard/ click on _Import a Project_
- import it (the .readthedocs.yml from the 2nd step is already added in this branch)
- once it is added click on the project select Admin > Advanced Settings > check the `Build pull requests for this project` box and save.

Now we should start to see preview builds in the pull request already.

**Comment by alexbovet** [comment]
Should I import the main branch?

**Comment by j-i-l** [comment]
Yes, I would keep it simple.

**Comment by alexbovet** [comment]
ok done

**Comment by j-i-l** [comment]
Great!
@alexbovet now, if you click on _Show al checks_ on the **All checks have passed** entry, and then on _Details_ on the docs/redthedocs.org:... you will see a preview of the docs.

**Comment by j-i-l** [comment]
@alexbovet If this is fine with you, I'd merge this branch into `main` as it contains a first functioning version of the documentation.
Better formatting the docstrings, adding examples and further details to the documentation can then be done separately.
Alternatively, we can keep on populating the documentation in this branch and merge it only once we are happy with the state of the documentation. The drawback here is only that this branch will then contain edits of most (if not all) `*.py` files and thus will be less straight forward to merge, if other edits happened in-between.

**Pull request merged**
